## Data wrangling and Cleaning for JSON files
In this notebook, I clean and wrangle the provided JSON files containing NBA prospect data. The goal is to standardize column names, handle missing values, and prepare the data for analysis.

In [2]:
import json
import pandas as pd

In [3]:
file_path = 'api_data_files/international_box_player_season.json'
with open(file_path, 'r') as f:
    json_data = json.load(f)
inter_box = pd.read_json(file_path)
nba_box = pd.read_json('api_data_files/nba_box_player_season.json')
player = pd.read_json('api_data_files/player.json')

In [4]:
inter_box.to_csv('inter.csv', index=False)
nba_box.to_csv('nba.csv', index=False)
player.to_csv('player.csv', index=False)

In [5]:
# inter_box.info()
inter_box['first_name'] = inter_box['first_name'].str.title()
inter_box['last_name'] = inter_box['last_name'].str.title()
nba_box['season'].unique()

array([2017, 2018, 2019, 2013, 2014, 2015, 2016, 2011, 2012, 2010, 2020,
       2021])

In [6]:
# nba_box.info()
nba_box['first_name'] = nba_box['first_name'].str.title()
nba_box['last_name'] = nba_box['last_name'].str.title()
nba_box

,first_name,last_name,season,season_type,league,team,games,starts,minutes,points,...,three_point_attempt_rate,free_throw_rate,offensive_rebounding_percentage,defensive_rebounding_percentage,total_rebounding_percentage,assist_percentage,steal_percentage,block_percentage,turnover_percentage,internal_box_plus_minus
0,Kadoshnikov,Christmas,2017,Full Season,NBA,Thunder,73,6,1135.2833,430,...,0.7253,0.1456,2.2515,8.3138,4.1831,7.9835,1.7237,0.6262,7.8512,-1.8309
1,Kadoshnikov,Christmas,2018,Full Season,NBA,Thunder,81,8,1243.8000,377,...,0.7524,0.1543,2.7414,10.2934,6.3177,5.7126,1.7110,1.1719,7.2601,-1.3166
2,Kadoshnikov,Christmas,2019,Full Season,NBA,Thunder,31,2,588.1667,165,...,0.8089,0.0828,0.9124,7.2142,4.8119,3.7177,1.5495,1.2268,7.9221,-3.1117
3,Kurucs,Humphrey,2013,Full Season,NBA,Raptors,29,0,342.3500,116,...,0.0267,0.5067,11.5375,18.4324,14.6673,6.3495,2.0357,3.8387,15.6365,0.0371
4,Kurucs,Humphrey,2014,Full Season,NBA,NaN,63,0,847.7000,171,...,0.0989,0.3701,11.0518,18.4784,14.5251,4.4947,1.5469,2.8704,15.6001,-1.7587
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1680,N'Doye,Nwaelele,2017,Full Season,NBA,Bulls,50,18,979.4333,284,...,0.4528,0.1890,2.8171,14.0662,9.1827,4.4250,0.9217,1.7990,14.5908,-4.3281
1681,N'Doye,Nwaelele,2018,Full Season,NBA,Bulls,54,12,823.8167,218,...,0.4701,0.1068,1.2273,16.4964,9.3931,10.7280,1.0850,1.9314,14.9306,-6.1027
1682,Mcfarlin,Nowitzki,2018,Full Season,NBA,Cavaliers,40,2,236.9833,132,...,0.0000,0.4545,13.2747,21.3207,16.4043,5.2298,0.5004,4.8256,12.3340,0.4038
1683,Mcfarlin,Nowitzki,2019,Full Season,NBA,Cavaliers,59,25,1082.0167,459,...,0.0000,0.3988,12.1883,21.4694,17.3244,8.9796,0.7295,2.2491,13.5531,-3.1735
1684,Mcfarlin,Nowitzki,2020,Full Season,NBA,Cavaliers,22,0,220.5833,96,...,0.0000,0.2639,8.1894,25.0595,16.0414,6.3944,1.4132,1.9929,11.0668,-2.9672

In [7]:
player.head()
player['first_name'] = player['first_name'].str.title()
player['last_name'] = player['last_name'].str.title()
player.head()

    first_name  last_name  birth_date
0         Theo     Greene  1995-12-26
1        Miles   Brussino  1993-02-01
2        Ayres  Bortolani  1969-01-20
3  Kadoshnikov  Christmas  1993-08-10
4      Rashawn         De  1989-08-30

In [8]:
combined = pd.concat([inter_box, nba_box])
combined.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5055 entries, 0 to 1684
Data columns (total 55 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   first_name                       5055 non-null   object
 1   last_name                        5055 non-null   object
 2   season                           5055 non-null   int64
 3   season_type                      5055 non-null   object
 4   league                           5055 non-null   object
 5   team                             4789 non-null   object
 6   games                            5055 non-null   int64
 7   starts                           5055 non-null   int64
 8   minutes                          5055 non-null   float64
 9   points                           5055 non-null   int64
 10  two_points_made                  5055 non-null   int64
 11  two_points_attempted             5055 non-null   int64
 12  three_points_made                5055 non-null   int64
 13  three_points_attempted           5055 non-null   int64
 14  free_throws_made                 5055 non-null   int64
 15  free_throws_attempted            5055 non-null   int64
 16  blocked_shot_attempts            5055 non-null   int64
 17  offensive_rebounds               5055 non-null   int64
 18  defensive_rebounds               5055 non-null   int64
 19  assists                          5055 non-null   int64
 20  screen_assists                   5055 non-null   int64
 21  turnovers                        5055 non-null   int64
 22  steals                           5055 non-null   int64
 23  deflections                      5055 non-null   int64
 24  loose_balls_recovered            5055 non-null   int64
 25  blocked_shots                    5055 non-null   int64
 26  personal_fouls                   5055 non-null   int64
 27  personal_fouls_drawn             5055 non-null   int64
 28  offensive_fouls                  5055 non-null   int64
 29  charges_drawn                    5055 non-null   int64
 30  technical_fouls                  5055 non-null   int64
 31  flagrant_fouls                   5055 non-null   int64
 32  ejections                        5055 non-null   int64
 33  points_off_turnovers             5055 non-null   int64
 34  points_in_paint                  5055 non-null   int64
 35  second_chance_points             5055 non-null   int64
 36  fast_break_points                5055 non-null   int64
 37  possessions                      5055 non-null   float64
 38  estimated_possessions            5055 non-null   float64
 39  team_possessions                 5055 non-null   float64
 40  usage_percentage                 5055 non-null   float64
 41  true_shooting_percentage         5002 non-null   float64
 42  three_point_attempt_rate         4995 non-null   float64
 43  free_throw_rate                  4995 non-null   float64
 44  offensive_rebounding_percentage  5055 non-null   float64
 45  defensive_rebounding_percentage  5055 non-null   float64
 46  total_rebounding_percentage      5055 non-null   float64
 47  assist_percentage                5055 non-null   float64
 48  steal_percentage                 5055 non-null   float64
 49  block_percentage                 5055 non-null   float64
 50  turnover_percentage              5013 non-null   float64
 51  internal_box_plus_minus          4998 non-null   float64
 52  plus_minus                       1685 non-null   float64
 53  calculated_possessions           1682 non-null   float64
 54  plays_used                       1682 non-null   float64
dtypes: float64(19), int64(31), object(5)
memory usage: 2.2+ MB

In [10]:
# join birth_date to first and last name
# notice capital vs non capital letters
# join data
merged_df = pd.merge(combined, player, on=['first_name', 'last_name'], how='left')
merged_df['birth_date'].unique()

merged_df.to_csv('merged.csv', index=False)

In [9]:
merged_df.isna().sum()
# merged_df["team"] = (
#     merged_df.groupby(["first_name", "last_name", "season"])["team"]
#     .transform(lambda x: x.ffill().bfill())
# )
# missing_teams = merged_df[merged_df["team"].isna()]
# print(len(missing_teams))
# missing_teams
# this did nothing so i guesss they are unique

first_name                            0
last_name                             0
season                                0
season_type                           0
league                                0
team                                266
games                                 0
starts                                0
minutes                               0
points                                0
two_points_made                       0
two_points_attempted                  0
three_points_made                     0
three_points_attempted                0
free_throws_made                      0
free_throws_attempted                 0
blocked_shot_attempts                 0
offensive_rebounds                    0
defensive_rebounds                    0
assists                               0
screen_assists                        0
turnovers                             0
steals                                0
deflections                           0
loose_balls_recovered                 0
blocked_shots                         0
personal_fouls                        0
personal_fouls_drawn                  0
offensive_fouls                       0
charges_drawn                         0
technical_fouls                       0
flagrant_fouls                        0
ejections                             0
points_off_turnovers                  0
points_in_paint                       0
second_chance_points                  0
fast_break_points                     0
possessions                           0
estimated_possessions                 0
team_possessions                      0
usage_percentage                      0
true_shooting_percentage             53
three_point_attempt_rate             60
free_throw_rate                      60
offensive_rebounding_percentage       0
defensive_rebounding_percentage       0
total_rebounding_percentage           0
assist_percentage                     0
steal_percentage                      0
block_percentage                      0
turnover_percentage                  42
internal_box_plus_minus              57
plus_minus                         3370
calculated_possessions             3373
plays_used                         3373
birth_date                          192
dtype: int64

In [10]:
# normalize first/last names into a single key to reduce mismatches
for df in [inter_box, nba_box, player]:
    df['first_name_norm'] = df['first_name'].astype(str).str.strip().str.lower()
    df['last_name_norm']  = df['last_name'].astype(str).str.strip().str.lower()
    df['full_name_norm']  = df['first_name_norm'] + '|' + df['last_name_norm']  # safe composite key

In [11]:
# boolean mask per row, then counts
inter_box['in_nba'] = inter_box['full_name_norm'].isin(nba_box['full_name_norm'])
inter_box['in_nba'].value_counts(dropna=False)   # shows how many True/False/NaN
inter_box['in_nba'].sum()                        # number of rows in inter_box that match nba_box
len(inter_box)                                   # total rows in inter_box

3370